spring:
  application:
    name: hello-world

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: Hello World API
